package app.span.android;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;

import android.Manifest;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.os.ResultReceiver;
import androidx.lifecycle.Lifecycle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
public final class PcToAndroidClipboardTest {
    // Generated by the Rust desktop implementation. This fixed vector proves
    // Rust X25519/HKDF/ChaCha20-Poly1305 packets remain Android-compatible.
    private static final String PC_ID = "rust-test-pc";
    private static final String PC_PUBLIC =
            "59716dbff7b07fe4ae16c18e7712a4a9d6036e9737f621f6f9e7144e9651241d";
    private static final String ANDROID_PRIVATE =
            "b34293c9e4883a86feb43c65fc1bfa806ab709e2465965727555301b5e0db991";
    private static final String ANDROID_PUBLIC =
            "bc8be9171b797e0f82222994e58411ab111db7832c2d0755f1208f4252d60066";
    private static final String NONCE = "fe73b77324bf874d744d4bc6";
    private static final String CIPHERTEXT =
            "3d5f060122a3ad13c0b30bd288e941ac9f2e4ebe0912c114459e098d00076719"
                    + "fc3060f3fd4b43b430dcaceb6d87b4b4";
    private static final String EXPECTED = "Rust PC to Android clipboard ✓";
    private static final String SECOND_EXPECTED = "Second PC clipboard update ✓";
    private static final String LOCAL_AFTER_REMOTE = "User clipboard must remain local ✓";
    private static final String BASELINE = "span-test-baseline";

    private Context context;
    private Context testContext;
    private final AtomicReference<String> probedClipboard = new AtomicReference<>();

    @Before public void setUp() throws Exception {
        context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        testContext = InstrumentationRegistry.getInstrumentation().getContext();
        context.stopService(new Intent(context, SpanReceiveService.class));
        long stopDeadline = System.currentTimeMillis() + 2000;
        while (SpanReceiveService.isRunning() && System.currentTimeMillis() < stopDeadline) {
            Thread.sleep(25);
        }
        probedClipboard.set(null);
        context.getSharedPreferences("span", Context.MODE_PRIVATE).edit()
                .clear()
                .putString("identity.id", "android-test")
                .putString("identity.name", "Android Test")
                .putString("identity.private", ANDROID_PRIVATE)
                .putString("identity.public", ANDROID_PUBLIC)
                .commit();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            InstrumentationRegistry.getInstrumentation().getUiAutomation()
                    .grantRuntimePermission(
                            context.getPackageName(), Manifest.permission.POST_NOTIFICATIONS);
        }
        new SpanStore(context).saveDevices(Collections.singletonList(new SpanDevice(
                PC_ID,
                "Rust Test PC",
                "windows",
                "127.0.0.1",
                PC_PUBLIC,
                true,
                System.currentTimeMillis())));
    }

    @After public void tearDown() {
        SpanReceiveService.stop(context);
        context.getSharedPreferences("span", Context.MODE_PRIVATE).edit().clear().commit();
    }

    @Test public void repeatedRustPcPacketsUpdateAndroidSystemClipboardInBackground()
            throws Exception {
        SpanTextPacket rustPacket = SpanTextPacket.parse(fixedRustPacket().trim());
        assertEquals(
                "Rust packet must decrypt on Android before testing the service",
                EXPECTED,
                SpanCrypto.decryptText(rustPacket, ANDROID_PRIVATE, PC_PUBLIC));

        SpanDevice trusted = new SpanStore(context).trustedDevice(PC_ID);
        assertNotNull("test PC must be present in the service trust store", trusted);
        assertEquals(PC_PUBLIC, trusted.publicKeyHex);

        try (ActivityScenario<MainActivity> activity = ActivityScenario.launch(MainActivity.class)) {
            SpanReceiveService.start(context);
            activity.onActivity(this::writeClipboardBaseline);

            // Put Span's UI in the background. Only its real foreground receiver
            // service remains active while both PC packets arrive.
            activity.moveToState(Lifecycle.State.CREATED);
            launchForegroundClipboardProbe();
            probedClipboard.set(null);
            sendRawPacketWithRetry(fixedRustPacket());
            // Android 10+ may accept or silently defer a background clipboard
            // write. Keep it durable until a focused Span window or the
            // accessibility overlay can verify the exact value.
            assertPendingEventuallyEquals(EXPECTED);
            closeForegroundProbe();
            activity.moveToState(Lifecycle.State.RESUMED);
            assertActivityClipboardEventuallyEquals(activity, EXPECTED);
            assertPendingEventuallyCleared();
            assertEquals(
                    "received clipboard text must not be echoed to its sender",
                    0,
                    SpanClipboardSync.sendCapturedClipboard(context, EXPECTED));

            // Simulate the user copying something in the foreground app after
            // the PC update. Bringing Span back must not replay the old pending
            // value over this newer local clipboard.
            setClipboardFromForegroundProbe(LOCAL_AFTER_REMOTE);
            closeForegroundProbe();
            activity.moveToState(Lifecycle.State.RESUMED);
            assertActivityClipboardEventuallyEquals(activity, LOCAL_AFTER_REMOTE);

            activity.moveToState(Lifecycle.State.CREATED);
            launchForegroundClipboardProbe();
            // A fresh encrypted packet exercises the production receive path a
            // second time, guarding against the observed "first copy only" bug.
            SpanCrypto.Encrypted second = SpanCrypto.encryptText(
                    SECOND_EXPECTED, ANDROID_PRIVATE, PC_PUBLIC);
            probedClipboard.set(null);
            sendRawPacketWithRetry(packetLine(second.nonceHex, second.ciphertextHex));
            assertPendingEventuallyEquals(SECOND_EXPECTED);
            closeForegroundProbe();
            activity.moveToState(Lifecycle.State.RESUMED);
            assertActivityClipboardEventuallyEquals(activity, SECOND_EXPECTED);
        }
    }

    private void writeClipboardBaseline(MainActivity activity) {
        ClipboardManager clipboard =
                (ClipboardManager) activity.getSystemService(Context.CLIPBOARD_SERVICE);
        assertNotNull(clipboard);
        clipboard.setPrimaryClip(ClipData.newPlainText("test baseline", BASELINE));
    }

    private String fixedRustPacket() {
        return packetLine(NONCE, CIPHERTEXT);
    }

    private String packetLine(String nonce, String ciphertext) {
        return SpanProtocol.TEXT_MAGIC + "\t" + PC_ID + "\t" + nonce + "\t"
                + ciphertext + "\n";
    }

    private void sendRawPacketWithRetry(String line) throws Exception {
        byte[] data = line.getBytes(StandardCharsets.UTF_8);
        Exception last = null;
        long deadline = System.currentTimeMillis() + 10000;
        while (System.currentTimeMillis() < deadline) {
            try (Socket socket = new Socket()) {
                socket.connect(new InetSocketAddress("127.0.0.1", SpanProtocol.TEXT_PORT), 500);
                OutputStream output = socket.getOutputStream();
                output.write(data);
                output.flush();
                return;
            } catch (Exception error) {
                last = error;
                Thread.sleep(100);
            }
        }
        if (last != null) throw last;
        throw new AssertionError("receiver did not start");
    }

    private void launchForegroundClipboardProbe() {
        Intent intent = new Intent();
        intent.setComponent(new ComponentName(
                testContext.getPackageName(), ClipboardProbeActivity.class.getName()));
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        intent.putExtra(ClipboardProbeActivity.EXTRA_FINISH_ON_VALUE, SECOND_EXPECTED);
        intent.putExtra(ClipboardProbeActivity.EXTRA_RESULT_RECEIVER, clipboardResultReceiver());
        testContext.startActivity(intent);
        try {
            Thread.sleep(500);
        } catch (InterruptedException error) {
            Thread.currentThread().interrupt();
            throw new AssertionError("interrupted while launching clipboard probe", error);
        }
    }

    private void setClipboardFromForegroundProbe(String value) throws Exception {
        probedClipboard.set(null);
        Intent intent = new Intent();
        intent.setComponent(new ComponentName(
                testContext.getPackageName(), ClipboardProbeActivity.class.getName()));
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        intent.putExtra(ClipboardProbeActivity.EXTRA_SET_VALUE, value);
        intent.putExtra(ClipboardProbeActivity.EXTRA_RESULT_RECEIVER, clipboardResultReceiver());
        testContext.startActivity(intent);
        assertClipboardEventuallyEquals(value);
    }

    private ResultReceiver clipboardResultReceiver() {
        return new ResultReceiver(null) {
            @Override protected void onReceiveResult(int resultCode, Bundle resultData) {
                if (resultCode == ClipboardProbeActivity.RESULT_CLIPBOARD && resultData != null) {
                    probedClipboard.set(resultData.getString(ClipboardProbeActivity.EXTRA_VALUE));
                }
            }
        };
    }

    private void closeForegroundProbe() throws Exception {
        Intent intent = new Intent();
        intent.setComponent(new ComponentName(
                testContext.getPackageName(), ClipboardProbeActivity.class.getName()));
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        intent.putExtra(ClipboardProbeActivity.EXTRA_FINISH_NOW, true);
        testContext.startActivity(intent);
        Thread.sleep(250);
    }

    private void assertActivityClipboardEventuallyEquals(
            ActivityScenario<MainActivity> activity, String expected) throws Exception {
        AtomicReference<String> actual = new AtomicReference<>();
        long deadline = System.currentTimeMillis() + 5000;
        while (System.currentTimeMillis() < deadline) {
            activity.onActivity(current -> {
                ClipboardManager clipboard = (ClipboardManager)
                        current.getSystemService(Context.CLIPBOARD_SERVICE);
                if (clipboard == null || !clipboard.hasPrimaryClip()) return;
                ClipData clip = clipboard.getPrimaryClip();
                if (clip == null || clip.getItemCount() == 0) return;
                CharSequence value = clip.getItemAt(0).coerceToText(current);
                actual.set(value == null ? null : value.toString());
            });
            if (expected.equals(actual.get())) return;
            Thread.sleep(100);
        }
        assertEquals(expected, actual.get());
    }

    private void assertClipboardEventuallyEquals(String expected) throws Exception {
        long deadline = System.currentTimeMillis() + 5000;
        String actual = null;
        while (System.currentTimeMillis() < deadline) {
            actual = probedClipboard.get();
            if (expected.equals(actual)) return;
            Thread.sleep(100);
        }
        assertEquals(expected, actual);
    }

    private void assertPendingEventuallyEquals(String expected) throws Exception {
        long deadline = System.currentTimeMillis() + 5000;
        String actual = null;
        while (System.currentTimeMillis() < deadline) {
            actual = context.getSharedPreferences("span", Context.MODE_PRIVATE)
                    .getString("clipboard.pending_remote_text", null);
            if (expected.equals(actual)) return;
            Thread.sleep(50);
        }
        assertEquals(expected, actual);
    }

    private void assertPendingEventuallyCleared() throws Exception {
        long deadline = System.currentTimeMillis() + 5000;
        while (System.currentTimeMillis() < deadline) {
            if (!context.getSharedPreferences("span", Context.MODE_PRIVATE)
                    .contains("clipboard.pending_remote_text")) return;
            Thread.sleep(50);
        }
        assertFalse(context.getSharedPreferences("span", Context.MODE_PRIVATE)
                .contains("clipboard.pending_remote_text"));
    }
}
